sonar.projectKey=tadak_web30-tadak
sonar.organization=tadak

# 소스
sonar.sources=apps/web/src,apps/api/src,apps/judge/src,packages

# 제외
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/pnpm-lock.yaml,**/.scannerwork/**,**/coverage/**

# 테스트 파일
sonar.tests=apps/web/src,apps/api/src,apps/judge/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx

# 커버리지 리포트
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info,apps/api/coverage/lcov.info,apps/judge/coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
